name: deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up job
        run: echo "Starting deploy job"

      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.148.2'
          extended: true

      - name: Install Hugo modules
        run: |
          hugo mod get || true

      - name: Build
        run: |
          hugo -D

      - name: Checkout destination
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: built-site

      - name: Copy built site
        run: |
          rm -rf built-site/*
          cp -R public/* built-site/

      - name: Configure git
        working-directory: built-site
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Check for changes
        id: changes
        working-directory: built-site
        shell: bash
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit and push
        if: steps.changes.outputs.changed == 'true'
        working-directory: built-site
        shell: bash
        run: |
          git commit -m "deploy: ${GITHUB_SHA}"
          git push origin gh-pages

      - name: Skip (no changes)
        if: steps.changes.outputs.changed != 'true'
        run: echo "No changes to deploy."

name: Publish to GH Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Checkout destination
        uses: actions/checkout@v3
        if: github.ref == 'refs/heads/main'
        with:
          ref: gh-pages
          path: built-site

      - name: Setup Hugo
        run: |
          curl -L -o /tmp/hugo.tar.gz 'https://github.com/gohugoio/hugo/releases/download/v0.147.0/hugo_extended_0.147.0_linux-amd64.tar.gz'
          tar -C ${RUNNER_TEMP} -zxvf /tmp/hugo.tar.gz hugo

      - name: Install Hugo modules
        run: ${RUNNER_TEMP}/hugo mod get

      - name: Build
        run: ${RUNNER_TEMP}/hugo

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          cp -R public/* ${GITHUB_WORKSPACE}/built-site/
          cd ${GITHUB_WORKSPACE}/built-site
          git add .
          git config user.name 'Abeer Agarwal'
          git config user.email '2006abeer.agarwal@gmail.com'
          git commit -m 'Updated site'
          git push
